apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: api-call-workflow
spec:
  entrypoint: api-call
  templates:
    - name: api-call
      container:
        image: curlimages/curl:latest
        command: [ "curl" ]
        args:
          - "-X"
          - "GET"
          - "https://jsonplaceholder.typicode.com/posts"

