apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: api-call-workflow
spec:
  entrypoint: api-call
  templates:
    - name: api-call
      container:
        image: curlimages/curl:latest
        command: [ "curl" ]
        args:
          - "-X"
          - "POST"
          - "http://your-api-service.com/api/v1/resource"
          - "-H"
          - "Content-Type: application/json"
          - "-d"
          - '{"key1":"value1", "key2":"value2"}'
